# https://fedoraproject.org/wiki/Packaging:Haskell

%global ghc_without_dynamic 1
%global ghc_without_shared 1
%global without_prof 1
%global without_haddock 1

%global pkg_name idris

# no useful debuginfo for Haskell packages without C sources
%global debug_package %{nil}

Name:           %{pkg_name}
Version:        0.9.14.3
Release:        1%{?dist}
Summary:        Functional Programming Language with Dependent Types

License:        BSD
Url:            http://hackage.haskell.org/package/%{name}
Source0:        http://hackage.haskell.org/package/%{name}-%{version}/%{name}-%{version}.tar.gz

BuildRequires:  ghc-Cabal-devel
BuildRequires:  ghc-rpm-macros
# Begin cabal-rpm deps:
#BuildRequires:  chrpath
#BuildRequires:  ghc-annotated-wl-pprint-devel
BuildRequires:  ghc-ansi-terminal-devel
BuildRequires:  ghc-ansi-wl-pprint-devel
BuildRequires:  ghc-base64-bytestring-devel
BuildRequires:  ghc-binary-devel
BuildRequires:  ghc-blaze-html-devel
BuildRequires:  ghc-blaze-markup-devel
BuildRequires:  ghc-bytestring-devel
#BuildRequires:  ghc-cheapskate-devel
BuildRequires:  ghc-containers-devel
BuildRequires:  ghc-deepseq-devel
BuildRequires:  ghc-directory-devel
BuildRequires:  ghc-filepath-devel
#BuildRequires:  ghc-fingertree-devel
BuildRequires:  ghc-haskeline-devel
BuildRequires:  ghc-language-java-devel
#BuildRequires:  ghc-lens-devel
BuildRequires:  ghc-mtl-devel
BuildRequires:  ghc-network-devel
BuildRequires:  ghc-optparse-applicative-devel
#BuildRequires:  ghc-parsers-devel
BuildRequires:  ghc-pretty-devel
BuildRequires:  ghc-process-devel
BuildRequires:  ghc-split-devel
BuildRequires:  ghc-text-devel
BuildRequires:  ghc-time-devel
BuildRequires:  ghc-transformers-devel
#BuildRequires:  ghc-trifecta-devel
BuildRequires:  ghc-unix-devel
BuildRequires:  ghc-unordered-containers-devel
BuildRequires:  ghc-utf8-string-devel
BuildRequires:  ghc-vector-binary-instances-devel
BuildRequires:  ghc-vector-devel
BuildRequires:  ghc-xml-devel
BuildRequires:  ghc-zlib-devel
# End cabal-rpm deps
BuildRequires:  cabal-dev
# for language-java
BuildRequires:  alex


%description
Idris is a general purpose language with full dependent types. It is compiled,
with eager evaluation. Dependent types allow types to be predicated on values,
meaning that some aspects of a program's behaviour can be specified precisely
in the type. The language is closely related to Epigram and Agda.
There is a tutorial at <http://www.idris-lang.org/documentation>.
Features include:

* Full dependent types with dependent pattern matching

* where clauses, with rule, simple case expressions, pattern matching let and
lambda bindings

* Type classes, monad comprehensions

* do notation, idiom brackets, syntactic conveniences for lists, tuples,
dependent pairs

* Totality checking

* Coinductive types

* Indentation significant syntax, extensible syntax

* Tactic based theorem proving (influenced by Coq)

* Cumulative universes

* Simple foreign function interface (to C)

* Hugs style interactive environment.


%prep
%setup -q


%build
[ -d "$HOME/.cabal" ] || cabal update
%global cabal cabal-dev -s %{_builddir}/cabal-dev
%cabal install language-java-0.2.6
%cabal install-deps
cabal_configure_extra_options=--ghc-option=-O1
%ghc_bin_build


%install
%ghc_bin_install

rm -r %{buildroot}%{ghclibdir}


%files
%doc LICENSE
%{_bindir}/idris-node
%{_bindir}/idris-javascript
%{_bindir}/idris-c
%{_bindir}/%{name}
%{_datadir}/%{name}-%{version}


%changelog
* Wed Sep 10 2014 Jens Petersen <petersen@redhat.com> - 0.9.14.3-1
- disable dyn, prof, docs
- use cabal-dev to build missing deps, and exclude library

* Wed Sep 10 2014 Fedora Haskell SIG <haskell@lists.fedoraproject.org> - 0.9.14.3
- spec file generated by cabal-rpm-0.9.1
